//! Output rendering: `.env`, Docker Compose, and config YAML files.

use std::fmt::Write;

use super::presets::AgentSlot;
use super::providers::Provider;

/// Derive a short model key from a full model name.
///
/// Examples:
///   - `"meta-llama/Llama-3-70b"` → `"llama-3-70b"`
///   - `"gpt-4o"` → `"gpt-4o"`
///   - `"opus"` → `"opus"`
///   - `""` → `"model"`
fn model_key_from_name(model_name: &str) -> String {
    // Take the part after the last '/' if present, then lowercase
    let base = model_name.rsplit('/').next().unwrap_or(model_name);
    let key = base.to_lowercase().replace(' ', "-").replace(
        |c: char| !c.is_alphanumeric() && c != '-' && c != '_' && c != '.',
        "-",
    );
    if key.is_empty() {
        "model".to_string()
    } else {
        key
    }
}

/// Escape a string for use inside a YAML double-quoted scalar.
fn escape_yaml_double_quoted(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

// ── Output rendering ───────────────────────────────────────────────────────

#[allow(clippy::too_many_arguments)]
pub(super) fn render_env(
    persona: &str,
    app_port: u16,
    nats_port: u16,
    api_secret: &str,
    worker_secret: &str,
    account_seed: &str,
    providers: &[Provider],
    orchestrator_url: Option<&str>, // for worker persona
    operator_name: Option<&str>,    // optional operator display name
) -> String {
    let mut out = String::new();
    let now = chrono::Local::now().format("%Y-%m-%d").to_string();

    writeln!(out, "# Generated by nsed-orchestrator init ({now})").unwrap();
    writeln!(
        out,
        "# WARNING: Keep this file SECRET. Never commit it to version control."
    )
    .unwrap();
    writeln!(out).unwrap();

    if persona == "owner" {
        writeln!(out, "# ----- Orchestrator -----").unwrap();
        writeln!(out, "APP_PORT={app_port}").unwrap();
        writeln!(out, "NATS_PORT={nats_port}").unwrap();
        writeln!(out).unwrap();
        writeln!(
            out,
            "# Admin token — full access including job deletion. Keep private."
        )
        .unwrap();
        writeln!(out, "APP_AUTH__ENABLED=true").unwrap();
        writeln!(out, "APP_AUTH__TOKENS__0__NAME=admin").unwrap();
        writeln!(out, "APP_AUTH__TOKENS__0__SECRET={api_secret}").unwrap();
        writeln!(out, "APP_AUTH__TOKENS__0__ROLES__0=user").unwrap();
        writeln!(out, "APP_AUTH__TOKENS__0__ROLES__1=admin").unwrap();
        writeln!(out).unwrap();
        writeln!(
            out,
            "# Worker token — safe to share with agent runners. Cannot delete jobs."
        )
        .unwrap();
        writeln!(out, "APP_AUTH__TOKENS__1__NAME=worker").unwrap();
        writeln!(out, "APP_AUTH__TOKENS__1__SECRET={worker_secret}").unwrap();
        writeln!(out, "APP_AUTH__TOKENS__1__ROLES__0=user").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "# \u{26a0}  Save APP_CREDENTIALS__ACCOUNT_SEED.").unwrap();
        writeln!(
            out,
            "#    If it changes, all registered agents must re-authenticate."
        )
        .unwrap();
        writeln!(out, "APP_CREDENTIALS__ENABLED=true").unwrap();
        writeln!(out, "APP_CREDENTIALS__ACCOUNT_SEED={account_seed}").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "# ----- Agent -----").unwrap();
    // Local agents use the worker token (user role only)
    let agent_token = if persona == "owner" {
        worker_secret
    } else {
        api_secret
    };
    writeln!(out, "NSED_BEARER_TOKEN={agent_token}").unwrap();
    if let Some(url) = orchestrator_url {
        writeln!(out, "NSED_ORCHESTRATOR_URL={url}").unwrap();
    }
    if let Some(name) = operator_name {
        let escaped = name
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace(['\r', '\n'], "");
        writeln!(out, "NSED_OPERATOR_NAME=\"{escaped}\"").unwrap();
    }

    // Agent signing seed — shared across all agents in this deployment.
    // Per-agent distinct keys will come with cryptographic identity (#115).
    let seed: [u8; 32] = rand::random();
    writeln!(
        out,
        "# Agent signing seed (Ed25519) — persistent identity for audit trail"
    )
    .unwrap();
    writeln!(out, "NSED_AGENT_SEED={}", hex::encode(seed)).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "# ----- LLM Provider API keys -----").unwrap();
    for p in providers {
        let env_key = p.id.to_uppercase().replace(['-', ' '], "_");
        match p.provider_type.as_str() {
            "simulated" => {
                writeln!(out, "# {}: no API key required", p.id).unwrap();
            }
            _ if p.is_local() => {
                writeln!(out, "# {}: local endpoint, no API key required", p.id).unwrap();
            }
            _ => {
                writeln!(
                    out,
                    "{env_key}_API_KEY={}",
                    p.api_key.as_deref().unwrap_or("<your-key-here>")
                )
                .unwrap();
            }
        }
    }

    // Provider base URLs — agents pick these up via env_file: .env
    let has_base_urls = providers
        .iter()
        .any(|p| p.provider_type != "simulated" && !p.base_url.is_empty());
    if has_base_urls {
        writeln!(out).unwrap();
        writeln!(out, "# ----- LLM Provider base URLs -----").unwrap();
        for p in providers {
            if p.provider_type == "simulated" || p.base_url.is_empty() {
                continue;
            }
            let env_key = p.id.to_uppercase().replace(['-', ' '], "_");
            writeln!(out, "APP_PROVIDERS__{env_key}__BASE_URL={}", p.base_url).unwrap();
        }
    }

    out
}

pub(super) fn render_compose_owner(
    app_port: u16,
    nats_port: u16,
    providers: &[Provider],
    agents: &[AgentSlot],
) -> String {
    let mut out = String::new();
    writeln!(out, "# Generated by nsed-orchestrator init").unwrap();
    writeln!(out, "# Start: docker compose up -d").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "services:").unwrap();

    // ── NATS JetStream ──────────────────────────────────────────────────
    writeln!(out, "  nats:").unwrap();
    writeln!(out, "    image: nats:2-alpine").unwrap();
    writeln!(
        out,
        "    command: [\"--jetstream\", \"--port\", \"{nats_port}\"]"
    )
    .unwrap();
    writeln!(out, "    ports:").unwrap();
    writeln!(out, r#"      - "${{NATS_PORT:-{nats_port}}}:{nats_port}""#).unwrap();
    writeln!(out, "    restart: unless-stopped").unwrap();
    writeln!(out, "    healthcheck:").unwrap();
    writeln!(
        out,
        r#"      test: ["CMD", "sh", "-c", "printf 'PING\r\n' | nc localhost {nats_port} | grep -q PONG"]"#
    )
    .unwrap();
    writeln!(out, "      interval: 5s").unwrap();
    writeln!(out, "      timeout: 3s").unwrap();
    writeln!(out, "      retries: 10").unwrap();
    writeln!(out).unwrap();

    // ── Orchestrator ────────────────────────────────────────────────────
    writeln!(out, "  nsed:").unwrap();
    writeln!(out, "    image: ghcr.io/peeramid-labs/nsed:latest").unwrap();
    writeln!(out, "    ports:").unwrap();
    writeln!(out, r#"      - "${{APP_PORT:-{app_port}}}:{app_port}""#).unwrap();
    writeln!(out, "    env_file: .env").unwrap();
    // Always emit `environment:` — the orchestrator needs NATS URL and host
    // override to bind 0.0.0.0 for container-to-host port forwarding.
    writeln!(out, "    environment:").unwrap();
    writeln!(out, "      APP_SERVER__HOST: \"0.0.0.0\"").unwrap();
    writeln!(out, "      APP_NATS__URL: \"nats://nats:{nats_port}\"").unwrap();
    let remote_providers: Vec<_> = providers
        .iter()
        .filter(|p| p.provider_type != "simulated" && !p.is_local())
        .collect();
    for p in &remote_providers {
        let id_upper = p.id.to_uppercase().replace(['-', ' '], "_");
        writeln!(
            out,
            "      APP_PROVIDERS__{id_upper}__API_KEY: ${{{id_upper}_API_KEY}}"
        )
        .unwrap();
    }
    writeln!(out, "    volumes:").unwrap();
    writeln!(
        out,
        "      - ./config/orchestrator.yml:/app/config/default.yml:ro"
    )
    .unwrap();
    writeln!(out, "    depends_on:").unwrap();
    writeln!(out, "      nats:").unwrap();
    writeln!(out, "        condition: service_healthy").unwrap();
    writeln!(out, "    restart: unless-stopped").unwrap();
    writeln!(out, "    healthcheck:").unwrap();
    writeln!(
        out,
        r#"      test: ["CMD", "curl", "-sf", "http://localhost:${{APP_PORT:-{app_port}}}/health"]"#
    )
    .unwrap();
    writeln!(out, "      interval: 10s").unwrap();
    writeln!(out, "      timeout: 5s").unwrap();
    writeln!(out, "      retries: 12").unwrap();
    writeln!(out).unwrap();

    for (i, agent) in agents.iter().enumerate() {
        let svc = format!("nsed-agent-{}", i + 1);
        let id_upper = agent.provider_id.to_uppercase().replace(['-', ' '], "_");
        writeln!(out, "  {svc}:").unwrap();
        writeln!(out, "    image: ghcr.io/peeramid-labs/nsed-agent:latest").unwrap();
        writeln!(out, "    env_file: .env").unwrap();
        writeln!(out, "    environment:").unwrap();
        writeln!(
            out,
            r#"      NSED_ORCHESTRATOR_URL: "http://nsed:${{APP_PORT:-{app_port}}}""#
        )
        .unwrap();
        writeln!(out, "      NSED_BEARER_TOKEN: ${{NSED_BEARER_TOKEN}}").unwrap();
        writeln!(out, "      NSED_AGENT_NAME: {}", agent.name).unwrap();
        if !agent.model_name.is_empty() {
            writeln!(out, "      NSED_MODEL: {}", agent.model_name).unwrap();
        }
        // Forward the provider base URL and API key
        let provider = providers.iter().find(|p| p.id == agent.provider_id);
        if let Some(p) = provider {
            if !p.base_url.is_empty() {
                writeln!(out, "      NSED_BASE_URL: {}", p.base_url).unwrap();
            }
            writeln!(out, "      NSED_PROVIDER: {}", agent.provider_id).unwrap();
            if p.provider_type != "simulated" && !p.is_local() {
                writeln!(
                    out,
                    "      APP_PROVIDERS__{id_upper}__API_KEY: ${{{id_upper}_API_KEY}}"
                )
                .unwrap();
            }
        }
        writeln!(out, "    volumes:").unwrap();
        writeln!(out, "      - ./config/agent.yml:/app/config/default.yml:ro").unwrap();
        writeln!(out, "    depends_on:").unwrap();
        writeln!(out, "      nsed:").unwrap();
        writeln!(out, "        condition: service_healthy").unwrap();
        writeln!(out, "    restart: unless-stopped").unwrap();
        writeln!(out).unwrap();
    }

    out
}

pub(super) fn render_compose_worker(agents: &[AgentSlot], providers: &[Provider]) -> String {
    let mut out = String::new();
    writeln!(out, "# Generated by nsed-orchestrator init (worker)").unwrap();
    writeln!(out, "# Start: docker compose up -d").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "services:").unwrap();

    for (i, agent) in agents.iter().enumerate() {
        let svc = format!("nsed-agent-{}", i + 1);
        let id_upper = agent.provider_id.to_uppercase().replace(['-', ' '], "_");
        writeln!(out, "  {svc}:").unwrap();
        writeln!(out, "    image: ghcr.io/peeramid-labs/nsed-agent:latest").unwrap();
        writeln!(out, "    env_file: .env").unwrap();
        writeln!(out, "    environment:").unwrap();
        writeln!(
            out,
            "      NSED_ORCHESTRATOR_URL: ${{NSED_ORCHESTRATOR_URL}}"
        )
        .unwrap();
        writeln!(out, "      NSED_BEARER_TOKEN: ${{NSED_BEARER_TOKEN}}").unwrap();
        writeln!(out, "      NSED_AGENT_NAME: {}", agent.name).unwrap();
        if !agent.model_name.is_empty() {
            writeln!(out, "      NSED_MODEL: {}", agent.model_name).unwrap();
        }
        let provider = providers.iter().find(|p| p.id == agent.provider_id);
        if let Some(p) = provider {
            if !p.base_url.is_empty() {
                writeln!(out, "      NSED_BASE_URL: {}", p.base_url).unwrap();
            }
            writeln!(out, "      NSED_PROVIDER: {}", agent.provider_id).unwrap();
            if p.provider_type != "simulated" && !p.is_local() {
                writeln!(
                    out,
                    "      APP_PROVIDERS__{id_upper}__API_KEY: ${{{id_upper}_API_KEY}}"
                )
                .unwrap();
            }
        }
        writeln!(out, "    volumes:").unwrap();
        writeln!(out, "      - ./config/agent.yml:/app/config/default.yml:ro").unwrap();
        writeln!(out, "    restart: unless-stopped").unwrap();
        writeln!(out).unwrap();
    }

    out
}

/// Build the docker compose CLI flag string for a non-default compose file name.
///
/// Returns `""` for standard names (`docker-compose.yml`, `compose.yml`),
/// otherwise ` -f <name>`.
pub(super) fn compose_flag(compose_name: &str) -> String {
    if compose_name != "docker-compose.yml" && compose_name != "compose.yml" {
        format!(" -f '{}'", compose_name.replace('\'', r"'\''"))
    } else {
        String::new()
    }
}

// ── Config YAML rendering ──────────────────────────────────────────────────

/// Render the agent `config/default.yml` file.
///
/// Produces:
///   - `orchestrators:` section (single entry pointing at the orchestrator URL)
///   - `providers:` section (one entry per provider with type, base_url, api_key, concurrency)
///   - `agents:` section (one entry per agent with model, temperature, max_tokens, etc.)
pub(super) fn render_agent_config(
    orchestrator_url: &str,
    providers: &[Provider],
    agents: &[AgentSlot],
) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# NSED Agent Configuration — Generated by nsed init").unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "#").unwrap();
    writeln!(
        out,
        "# Override values by creating config/local.yml or via environment variables."
    )
    .unwrap();
    writeln!(out).unwrap();

    // ── Orchestrators ───────────────────────────────────────────────────────
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# Orchestrators").unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(
        out,
        "# Agents register with each orchestrator via JWT challenge-response."
    )
    .unwrap();
    writeln!(
        out,
        "# The NATS URL is obtained from the orchestrator during registration."
    )
    .unwrap();
    writeln!(out, "orchestrators:").unwrap();
    writeln!(out, "  - id: \"primary\"").unwrap();
    writeln!(out, "    url: \"{}\"", orchestrator_url).unwrap();
    writeln!(out, "    bearer_token: \"${{NSED_BEARER_TOKEN}}\"").unwrap();
    writeln!(out, "#  - id: \"secondary\"").unwrap();
    writeln!(out, "#    url: \"http://orch-2:8080\"").unwrap();
    writeln!(out, "#    bearer_token: \"${{NSED_BEARER_TOKEN_2}}\"").unwrap();
    writeln!(out).unwrap();

    // ── Providers ───────────────────────────────────────────────────────────
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# LLM Providers").unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(
        out,
        "# Provider types: openai (OpenAI-compatible), exec (external process), simulated (testing)"
    )
    .unwrap();
    writeln!(out, "#").unwrap();
    writeln!(out, "# Engine strategies control LLM protocol:").unwrap();
    writeln!(
        out,
        "#   (default)          — standard OpenAI /chat/completions, streaming OK"
    )
    .unwrap();
    writeln!(
        out,
        "#   \"harmony\"          — GPT-OSS Harmony protocol (/completions)"
    )
    .unwrap();
    writeln!(
        out,
        "#   \"vllm\"             — vLLM XML tool format, no streaming"
    )
    .unwrap();
    writeln!(
        out,
        "#   \"vllm_responses\"   — vLLM Responses API (/responses)"
    )
    .unwrap();
    writeln!(out, "providers:").unwrap();
    // Build per-provider model entries and a map from agent name → resolved model key.
    // Each agent gets its own model entry; if two agents on the same provider
    // derive the same key, a suffix is appended to disambiguate.
    let mut provider_model_entries: std::collections::HashMap<
        String,
        Vec<(String, String, &AgentSlot)>,
    > = std::collections::HashMap::new();
    let mut agent_model_keys: std::collections::HashMap<String, String> =
        std::collections::HashMap::new();
    {
        let mut provider_key_counts: std::collections::HashMap<
            String,
            std::collections::HashMap<String, usize>,
        > = std::collections::HashMap::new();
        for agent in agents {
            let base_key = model_key_from_name(&agent.model_name);
            let counts = provider_key_counts
                .entry(agent.provider_id.clone())
                .or_default();
            let count = counts.entry(base_key.clone()).or_insert(0);
            let key = if *count == 0 {
                base_key.clone()
            } else {
                format!("{}-{}", base_key, count)
            };
            *counts.get_mut(&base_key).unwrap() += 1;
            agent_model_keys.insert(agent.name.clone(), key.clone());
            provider_model_entries
                .entry(agent.provider_id.clone())
                .or_default()
                .push((key, agent.model_name.clone(), agent));
        }
    }

    for p in providers {
        writeln!(out, "  {}:", p.id).unwrap();
        writeln!(out, "    type: {}", p.provider_type).unwrap();
        if !p.base_url.is_empty() {
            writeln!(out, "    base_url: \"{}\"", p.base_url).unwrap();
        }
        match p.provider_type.as_str() {
            "simulated" => {
                writeln!(out, "    latency_ms: 400").unwrap();
                writeln!(out, "    concurrency: 100").unwrap();
            }
            "exec" | "claude" => {
                // Exec/Claude providers have no additional config at the provider level.
            }
            _ if p.is_local() => {
                writeln!(out, "    api_key: \"ollama\"").unwrap();
                writeln!(out, "    concurrency: 1000").unwrap();
            }
            _ => {
                let env_key = p.id.to_uppercase().replace(['-', ' '], "_");
                writeln!(out, "    api_key: \"${{{env_key}_API_KEY}}\"").unwrap();
                writeln!(out, "    concurrency: 500").unwrap();
                writeln!(out, "    qps: 50").unwrap();
            }
        }
        if let Some(ref engine) = p.engine {
            writeln!(out, "    engine: \"{}\"", engine).unwrap();
        }

        // ── models: block ──────────────────────────────────────────────────
        if let Some(entries) = provider_model_entries.get(&p.id) {
            if !entries.is_empty() {
                writeln!(out, "    models:").unwrap();
                for (model_key, model_name, agent) in entries {
                    writeln!(out, "      {}:", model_key).unwrap();
                    writeln!(
                        out,
                        "        model_name: \"{}\"",
                        escape_yaml_double_quoted(model_name)
                    )
                    .unwrap();
                    writeln!(out, "        temperature: {:.1}", agent.temperature).unwrap();
                    writeln!(out, "        max_tokens: {}", agent.max_tokens).unwrap();
                    writeln!(
                        out,
                        "        presence_penalty: {:.1}",
                        agent.presence_penalty
                    )
                    .unwrap();
                    if let Some(cw) = agent.context_window {
                        writeln!(out, "        context_window: {}", cw).unwrap();
                    }
                    if let Some(ref re) = agent.reasoning_effort {
                        writeln!(out, "        reasoning_effort: \"{}\"", re).unwrap();
                    }
                    // Pricing
                    if let Some(ip) = agent.input_price {
                        writeln!(out, "        input_price_per_mtok: {:.2}", ip).unwrap();
                    }
                    if let Some(op) = agent.output_price {
                        writeln!(out, "        output_price_per_mtok: {:.2}", op).unwrap();
                    }
                    // Strategy flags (only emit when explicitly set)
                    if let Some(v) = agent.use_streaming {
                        writeln!(out, "        use_streaming: {}", v).unwrap();
                    }
                    if let Some(v) = agent.merge_system_prompt {
                        writeln!(out, "        merge_system_prompt: {}", v).unwrap();
                    }
                    if let Some(v) = agent.unwrap_hallucinated_tool_calls {
                        writeln!(out, "        unwrap_hallucinated_tool_calls: {}", v).unwrap();
                    }
                    if let Some(v) = agent.repair_invalid_escapes {
                        writeln!(out, "        repair_invalid_escapes: {}", v).unwrap();
                    }
                    if let Some(v) = agent.json_mode {
                        writeln!(out, "        json_mode: {}", v).unwrap();
                    }
                    if let Some(v) = agent.disable_native_tools {
                        writeln!(out, "        disable_native_tools: {}", v).unwrap();
                    }
                    if let Some(v) = agent.scratchpad_limit {
                        writeln!(out, "        scratchpad_limit: {}", v).unwrap();
                    }
                }
            }
        }
        writeln!(out).unwrap();
    }

    // ── Agents ──────────────────────────────────────────────────────────────
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# Agents").unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "agents:").unwrap();
    for agent in agents {
        writeln!(out, "  - name: \"{}\"", agent.name).unwrap();

        // Use dotpath model reference: "provider_id.model_key"
        let model_key = agent_model_keys
            .get(&agent.name)
            .cloned()
            .unwrap_or_else(|| model_key_from_name(&agent.model_name));
        writeln!(out, "    model: \"{}.{}\"", agent.provider_id, model_key).unwrap();

        // Exec provider: emit exec config block
        if let Some(ref cmd) = agent.exec_command {
            let parts: Vec<String> = cmd
                .iter()
                .map(|p| format!("\"{}\"", escape_yaml_double_quoted(p)))
                .collect();
            writeln!(out, "    exec:").unwrap();
            writeln!(out, "      command: [{}]", parts.join(", ")).unwrap();
        }

        // Persona
        if let Some(ref persona) = agent.persona {
            writeln!(
                out,
                "    persona: \"{}\"",
                escape_yaml_double_quoted(persona)
            )
            .unwrap();
        } else {
            writeln!(out, "    # persona: \"You are a helpful AI assistant.\"").unwrap();
        }

        // Capability tags for policy-based scheduling
        if agent.capability_tags.is_empty() {
            writeln!(out, "    # capability_tags: [\"general\", \"reasoning\"]").unwrap();
        } else {
            let tags: Vec<String> = agent
                .capability_tags
                .iter()
                .map(|t| format!("\"{}\"", escape_yaml_double_quoted(t)))
                .collect();
            writeln!(out, "    capability_tags: [{}]", tags.join(", ")).unwrap();
        }
        if let Some(ref desc) = agent.description {
            writeln!(
                out,
                "    description: \"{}\"",
                escape_yaml_double_quoted(desc)
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "    # description: \"Short description of this agent\""
            )
            .unwrap();
        }

        // Remaining optional fields (always commented — rarely changed)
        writeln!(out, "    # textual_feedback: true").unwrap();
        writeln!(out, "    # max_react_iterations: 10").unwrap();
        writeln!(out, "    # max_retries: 3").unwrap();
        writeln!(out, "    # failure_dumps: \"on\"").unwrap();
        writeln!(out).unwrap();
    }

    out
}

/// Render the orchestrator `config/default.yml` file.
///
/// Produces:
///   - `server:` section (port)
///   - `nats:` section (url)
///   - `providers:` section (mirror of agent providers for dashboard display)
///   - `auth:` section (enabled, tokens handled via .env)
///   - `credentials:` section (NKey JWT)
///   - `orchestrator:` section (commented-out tunables)
pub(super) fn render_orchestrator_config(
    app_port: u16,
    nats_port: u16,
    providers: &[Provider],
) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(
        out,
        "# NSED Orchestrator Configuration — Generated by nsed init"
    )
    .unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "#").unwrap();
    writeln!(
        out,
        "# Override values by creating config/local.yml or via environment variables"
    )
    .unwrap();
    writeln!(out, "# with the APP_ prefix (e.g. APP_SERVER__PORT=9090).").unwrap();
    writeln!(out).unwrap();

    // ── Server ──────────────────────────────────────────────────────────────
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# Server").unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "server:").unwrap();
    writeln!(
        out,
        "  # host: 127.0.0.1  # override via APP_SERVER__HOST (0.0.0.0 inside Docker)"
    )
    .unwrap();
    writeln!(out, "  port: {app_port}").unwrap();
    writeln!(out).unwrap();

    // ── NATS ────────────────────────────────────────────────────────────────
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# NATS JetStream").unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "nats:").unwrap();
    writeln!(out, "  url: \"nats://127.0.0.1:{nats_port}\"").unwrap();
    writeln!(out).unwrap();

    // ── Providers ───────────────────────────────────────────────────────────
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# LLM Providers (used by dashboard for display)").unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    if providers.is_empty() {
        writeln!(out, "# providers:").unwrap();
        writeln!(
            out,
            "#   (configured via environment variables or dashboard)"
        )
        .unwrap();
    } else {
        writeln!(out, "providers:").unwrap();
    }
    for p in providers {
        writeln!(out, "  {}:", p.id).unwrap();
        writeln!(out, "    type: {}", p.provider_type).unwrap();
        if !p.base_url.is_empty() {
            writeln!(out, "    base_url: \"{}\"", p.base_url).unwrap();
        }
        match p.provider_type.as_str() {
            "simulated" => {
                writeln!(out, "    latency_ms: 400").unwrap();
                writeln!(out, "    concurrency: 100").unwrap();
            }
            "exec" | "claude" => {}
            _ if p.is_local() => {
                writeln!(out, "    api_key: \"ollama\"").unwrap();
                writeln!(out, "    concurrency: 1000").unwrap();
            }
            _ => {
                let env_key = p.id.to_uppercase().replace(['-', ' '], "_");
                writeln!(
                    out,
                    "    #api_key: \"${{{env_key}_API_KEY}}\"  # Set via env var"
                )
                .unwrap();
                writeln!(out, "    concurrency: 500").unwrap();
                writeln!(out, "    qps: 50").unwrap();
            }
        }
        if let Some(ref engine) = p.engine {
            writeln!(out, "    engine: \"{}\"", engine).unwrap();
        }
        writeln!(out).unwrap();
    }

    // ── Auth ────────────────────────────────────────────────────────────────
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# Authentication").unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(
        out,
        "# Tokens are configured via .env (APP_AUTH__TOKENS__N__SECRET)."
    )
    .unwrap();
    writeln!(out, "auth:").unwrap();
    writeln!(out, "  enabled: true").unwrap();
    writeln!(out).unwrap();

    // ── Credentials ─────────────────────────────────────────────────────────
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# NATS JWT Credentials (Per-Agent Subject Isolation)").unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "credentials:").unwrap();
    writeln!(out, "  enabled: true").unwrap();
    writeln!(
        out,
        "  # account_seed is set via .env (APP_CREDENTIALS__ACCOUNT_SEED)"
    )
    .unwrap();
    writeln!(out, "  jwt_expiry_secs: 86400").unwrap();
    writeln!(out, "  challenge_expiry_secs: 300").unwrap();
    writeln!(out).unwrap();

    // ── Logging ─────────────────────────────────────────────────────────────
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# Logging").unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "logging:").unwrap();
    writeln!(out, "  level: \"info\"").unwrap();
    writeln!(out).unwrap();

    // ── Orchestrator ────────────────────────────────────────────────────────
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# Orchestrator").unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(
        out,
        "# All fields have sensible defaults — uncomment to customise."
    )
    .unwrap();
    writeln!(out, "#").unwrap();
    writeln!(out, "# orchestrator:").unwrap();
    writeln!(out, "#   subject_prefix: \"sphera\"").unwrap();
    writeln!(out, "#   default_job_timeout_secs: 3600").unwrap();
    writeln!(out, "#   agent_response_timeout_secs: 600").unwrap();
    writeln!(out, "#   status_retention_secs: 259200").unwrap();
    writeln!(out, "#   history_retention_secs: 604800").unwrap();
    writeln!(out, "#   scratchpad_retention_secs: 604800").unwrap();
    writeln!(out).unwrap();

    // ── NSED Protocol ───────────────────────────────────────────────────────
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# NSED Protocol Settings").unwrap();
    writeln!(
        out,
        "# ============================================================================="
    )
    .unwrap();
    writeln!(out, "# nsed:").unwrap();
    writeln!(out, "#   textual_feedback: true").unwrap();
    writeln!(out, "#   force_last_round_selection: true").unwrap();

    out
}

/// Public convenience wrapper — generates a full orchestrator config YAML
/// with sensible defaults and no provider block (providers can be added later).
///
/// Reused by `nsed init` when scaffolding an embedded orchestrator config file.
pub fn render_default_orchestrator_config(app_port: u16, nats_port: u16) -> String {
    render_orchestrator_config(app_port, nats_port, &[])
}
